version: app/v1
services:
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
  crowdfunding-dotnetcore:
    image: aryarana/crowdfunding-dotnetcore
    depends_on:
      - rabbitmq
    ports:
      - "8080:80"
