apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      name: rabbitmq
      targetPort: 5672
    - protocol: TCP
      port: 15672
      name: rabbitmq-dev
      targetPort: 15672
